"""Module AREAS for angel.co."""


AREAS = {
    "NY": {
        "New York City",
        "Brooklyn",
        "Rochester",
        "Erie County",
        "Buffalo",
        "Shirley",
        "Syracuse",
        "Ithaca",
        "Albany",
        "Manhattan",
        "White Plains",
        "Troy",
        "Queens",
        "Saratoga Springs",
        "Melville",
        "Bronx",
        "Suffolk County",
        "Huntington",
        "Binghamton",
        "Niagara Falls",
        "Stony Brook",
        "Yonkers",
        "Nassau County",
        "Hicksville",
        "Port Washington",
        "Garden City",
        "Schenectady",
        "Poughkeepsie",
        "Kingston",
        "Hauppauge",
        "New Rochelle",
        "Middletown",
        "Rye",
        "Utica",
        "Mineola",
        "Rockland County",
        "Rye Brook",
        "Brentwood",
        "Syosset",
        "Great Neck",
        "Hempstead",
        "Amsterdam",
        "Uniondale",
        "Jericho",
        "Montgomery County",
        "Mount Vernon",
        "Lockport",
        "Valley Stream",
        "Plainview",
        "Merrick",
        "Glens Falls",
        "Glen Cove",
        "Orange County",
        "Westchester County",
        "Scarsdale",
        "Tarrytown",
        "Bay Shore",
        "Westbury",
        "Long Beach",
        "Corning",
        "Oneonta",
        "Potsdam",
        "Newburgh",
        "Lynbrook",
        "Wantagh",
        "Medford",
        "Lewis County",
        "Monroe County",
        "Commack",
        "Massapequa",
        "Mount Kisco",
        "Elmont",
        "Oceanside",
        "Beacon",
        "Ossining",
        "Bellmore",
        "Staten Island",
        "Onondaga County",
        "Dutchess County",
        "Mamaroneck",
        "Floral Park",
        "New City",
        "Nanuet",
        "Suffern",
        "Auburn",
        "Dunkirk",
        "Hartsdale",
        "Canandaigua",
        "Harrison",
        "Levittown",
        "Monsey",
        "Baldwin",
        "East Northport",
        "Bethpage",
        "Rome",
        "Huntington Station",
        "Seaford",
        "Putnam County",
        "Ulster County",
        "Ontario County",
        "Tioga County",
        "Geneva",
        "Ronkonkoma",
        "Smithtown",
        "Freeport",
        "Newark",
        "Oswego",
        "Endicott",
        "Plattsburgh",
        "Oneida",
        "Woodmere",
        "Dobbs Ferry",
        "Roosevelt",
        "Deer Park",
        "Holbrook",
        "West Babylon",
        "Hamburg",
        "Bohemia",
        "Spring Valley",
        "East Meadow",
        "Fulton",
        "Central Islip",
        "Centereach",
        "Franklin Square",
        "Lancaster",
        "North Lindenhurst",
        "West Islip",
        "Bronxville",
        "Armonk",
        "Madison County",
        "Sullivan County",
        "Wayne County",
        "New York County",
        "Oneida County",
        "Columbia County",
        "Elmsford",
        "Larchmont",
        "Essex County",
        "Olean",
        "North Babylon",
        "Port Chester",
        "Copiague",
        "Jamestown",
        "Fredonia",
        "Peekskill",
        "Greece",
        "Sayville",
        "New Hyde Park",
        "Lake Grove",
        "Amityville",
        "Cortland",
        "Lake Ronkonkoma",
        "Holtsville",
        "Rotterdam",
        "Brighton",
        "Farmingville",
        "Saint James",
        "East Islip",
        "Port Jervis",
        "Coram",
        "Ogdensburg",
        "Depew",
        "Elwood",
        "North Massapequa",
        "Clifton Park Center",
        "Broome County",
        "Greene County",
        "Latham",
        "Queens County",
        "Otsego County",
        "Chappaqua",
        "Edinburg",
        "Herkimer County",
        "Ridgewood",
        "Irvington",
        "St. Lawrence County",
        "Genesee County",
        "Pleasantville",
        "Village of Pelham",
        "Rensselaer",
        "Oswego County",
        "Haverstraw",
        "Stony Point",
        "West Hempstead",
        "South Farmingdale",
        "West Haverstraw",
        "Eastchester",
        "East Patchogue",
        "East Rockaway",
        "Dix Hills",
        "Babylon",
        "Elmira",
        "Patchogue",
        "Tonawanda",
        "Cohoes",
        "Massapequa Park",
        "Sleepy Hollow",
        "Kenmore",
        "Nesconset",
        "Watertown",
        "North Tonawanda",
        "Islip",
        "Mastic Beach",
        "Massena",
        "Pearl River",
        "North Bellmore",
        "Gloversville",
        "Cheektowaga",
        "Mastic",
        "North Amityville",
        "Fairmount",
        "Kings Park",
        "Terryville",
        "Selden",
        "South Huntington",
        "Watervliet",
        "North Bay Shore",
        "North Merrick",
        "West Seneca",
        "Johnson City",
        "Lackawanna",
        "Endwell",
        "Katonah",
        "Bronx County",
        "Briarcliff Manor",
        "Croton-on-Hudson",
        "North Salem",
        "Ballston Spa",
        "Waterford",
        "Yorktown Heights",
        "Delaware County",
        "Bedford Hills",
        "Nashville",
        "Franklin County",
        "Washington County",
        "Livingston County",
        "Allegany County",
        "Hastings-on-Hudson",
        "Delmar",
        "Rensselaer County",
        "Fulton County",
        "Steuben County",
        "Bedford",
        "Cortlandt Manor",
        "Schuyler County",
        "Cortland County",
        "Seneca County",
        "Chautauqua County",
        "Wilson",
        "Halfmoon",
        "Schenectady County",
        "Waccabuc",
        "Charlton",
        "Croton Falls",
        "Chemung County",
        "Valhalla",
        "Guilderland",
        "Clinton County",
        "Millwood",
        "Slingerlands",
        "South Salem",
        "Schaghticoke",
        "Chenango County",
        "Porter Corners",
        "Hawthorne",
        "East Greenbush",
        "Altamont",
        "Warren County",
        "Malta",
        "Wyoming County",
        "Youngstown",
        "Jefferson Valley-Yorktown",
        "Jefferson County",
        "Interlaken",
        "Pound Ridge",
        "East Glenville",
        "Ballston Lake",
        "Ardsley",
        "Tuckahoe",
        "Pelham Manor",
        "Rotterdam Junction",
        "McGraw",
        "Goldens Bridge",
        "Cayuga County",
        "Lewiston",
        "Wilton",
        "Thornwood"
    },
    "CA": {
        "Northern California",
        "San Francisco Bay Area",
        "Silicon Valley",
        "San Francisco",
        "Southern California",
        "Palo Alto",
        "San Jose",
        "Mountain View",
        "Santa Clara",
        "Sunnyvale",
        "Oakland",
        "Alameda County",
        "San Mateo",
        "Menlo Park",
        "Berkeley",
        "Redwood City",
        "Sacramento",
        "Fremont",
        "California City",
        "Cupertino",
        "Pleasanton",
        "Los Altos",
        "Burlingame",
        "Santa Cruz",
        "Los Gatos",
        "Milpitas",
        "San Luis Obispo",
        "Campbell",
        "Marin County",
        "Walnut Creek",
        "San Ramon",
        "San Carlos",
        "Ontario",
        "South San Francisco",
        "Stanford",
        "El Segundo",
        "Emeryville",
        "Fresno",
        "Foster City",
        "Hayward",
        "San Rafael",
        "Santa Rosa",
        "Santa Ana",
        "Marina del Rey",
        "Livermore",
        "Orange",
        "Chico",
        "Davis",
        "Napa",
        "Monterey",
        "Alameda",
        "Ventura County",
        "Petaluma",
        "Saratoga",
        "Encinitas",
        "Ventura",
        "Mill Valley",
        "Sausalito",
        "Temecula",
        "San Bruno",
        "Calabasas",
        "Newark",
        "Walnut",
        "Belmont",
        "Bakersfield",
        "Dublin",
        "Agoura Hills",
        "San Leandro",
        "Roseville",
        "Folsom",
        "Novato",
        "Palm Springs",
        "Stockton",
        "Palmdale",
        "Camarillo",
        "Los Angeles County",
        "Danville",
        "Union City",
        "Contra Costa County",
        "Lafayette",
        "Richmond",
        "Fullerton",
        "Rocklin",
        "Oxnard",
        "Laguna Hills",
        "Lake Forest",
        "Pleasant Hill",
        "Scotts Valley",
        "Gardena",
        "Sonoma County",
        "Palm Desert",
        "Fountain Valley",
        "Woodside",
        "San Juan Capistrano",
        "Truckee",
        "Murrieta",
        "Millbrae",
        "Claremont",
        "Modesto",
        "Burbank",
        "Los Altos Hills",
        "Redding",
        "Laguna Niguel",
        "Elk Grove",
        "Larkspur",
        "Concord",
        "Rancho Santa Margarita",
        "Fairfield",
        "Morgan Hill",
        "Garden Grove",
        "Hawthorne",
        "Rancho Cordova",
        "San Mateo County",
        "Vallejo",
        "Diamond Bar",
        "Pacifica",
        "Buena Park",
        "Half Moon Bay",
        "West Covina",
        "Chino Hills",
        "Chula Vista",
        "Cerritos",
        "Poway",
        "La Mirada",
        "Pomona",
        "Lancaster",
        "Rohnert Park",
        "Daly City",
        "Vacaville",
        "Dana Point",
        "San Marcos",
        "Redlands",
        "National City",
        "El Cajon",
        "Tracy",
        "East Palo Alto",
        "Antioch",
        "Monrovia",
        "Rancho Palos Verdes",
        "Salinas",
        "Whittier",
        "South Lake Tahoe",
        "Moreno Valley",
        "Downey",
        "Glendora",
        "Pittsburg",
        "San Diego County",
        "Orinda",
        "San Bernardino",
        "Yorba Linda",
        "El Monte",
        "San Dimas",
        "Grass Valley",
        "Palos Verdes Estates",
        "Riverside County",
        "West Sacramento",
        "Hillsborough",
        "Corte Madera",
        "Citrus Heights",
        "Clovis",
        "La Quinta",
        "La Verne",
        "Sonoma",
        "La Jolla",
        "Healdsburg",
        "Moorpark",
        "Alamo",
        "Carmichael",
        "Baldwin Park",
        "Santee",
        "Alhambra",
        "Compton",
        "Rowland Heights",
        "Napa County",
        "Aptos",
        "Albany",
        "Benicia",
        "San Fernando",
        "Seal Beach",
        "Monterey Park",
        "La Cañada Flintridge",
        "Santa Maria",
        "Santa Fe Springs",
        "Signal Hill",
        "San Gabriel",
        "Fontana",
        "Martinez",
        "Hercules",
        "Fair Oaks",
        "Rosemead",
        "Twentynine Palms",
        "San Bernardino County",
        "Placer County",
        "Siskiyou County",
        "Cypress",
        "Carpinteria",
        "Lodi",
        "Bellflower",
        "Woodland",
        "Imperial Beach",
        "Lemon Grove",
        "Yuba City",
        "Capitola",
        "Hemet",
        "La Mesa",
        "Lawndale",
        "Westminster",
        "Colton",
        "Duarte",
        "Norwalk",
        "Artesia",
        "San Luis Obispo County",
        "Castro Valley",
        "Coronado",
        "Azusa",
        "Visalia",
        "Merced",
        "Ukiah",
        "Los Alamitos",
        "Lake Elsinore",
        "Rancho Mirage",
        "Lynwood",
        "Lincoln",
        "South El Monte",
        "La Habra",
        "Oakley",
        "La Palma",
        "Rio Linda",
        "South Gate",
        "Nevada County",
        "El Dorado County",
        "Mendocino County",
        "El Cerrito",
        "Pico Rivera",
        "Covina",
        "Victorville",
        "Rialto",
        "San Pablo",
        "Windsor",
        "Stanton",
        "Chino",
        "La Puente",
        "Manteca",
        "Hawaiian Gardens",
        "Soquel",
        "Eureka",
        "Lakewood",
        "Paramount",
        "Arcata",
        "Montebello",
        "Lomita",
        "Sierra Madre",
        "Yucaipa",
        "Commerce",
        "Galt",
        "Bell Gardens",
        "Orangevale",
        "Santa Clara County",
        "Monterey County",
        "Del Mar",
        "City of Industry",
        "Merced County",
        "Rancho San Diego",
        "Piedmont",
        "Loma Linda",
        "Morro Bay",
        "Moraga",
        "Pacific Grove",
        "Apple Valley",
        "Pinole",
        "Hesperia",
        "Huntington Park",
        "Auburn",
        "Westmont",
        "Placerville",
        "Cudahy",
        "Rolling Hills Estates",
        "Perris",
        "Hacienda Heights",
        "Cameron Park",
        "Gilroy",
        "Suisun City",
        "Laguna Woods",
        "Watsonville",
        "Ramona",
        "Indio",
        "Seaside",
        "Lathrop",
        "Barstow",
        "Patterson",
        "Atascadero",
        "El Sobrante",
        "San Marino",
        "North Highlands",
        "Marina",
        "Madera",
        "Roseland",
        "Cathedral City",
        "Calexico",
        "Beaumont",
        "Santa Paula",
        "Hollister",
        "Lakeside",
        "Wildomar",
        "Maywood",
        "Paradise",
        "Ashland",
        "Riverbank",
        "Cherryland",
        "Topanga",
        "Rancho Santa Fe",
        "Humboldt County",
        "Kern County",
        "Shasta County",
        "Sacramento County",
        "Lake County",
        "Madera County",
        "Chatsworth",
        "North Tustin",
        "Grover Beach",
        "Blythe",
        "Reedley",
        "Tulare",
        "Montclair",
        "Taft",
        "Coachella",
        "South San Jose Hills",
        "Clayton",
        "Temple City",
        "Orange Cove",
        "Arroyo Grande",
        "Isla Vista",
        "El Centro",
        "Crestline",
        "Lindsay",
        "Corcoran",
        "Canyon Lake",
        "Bostonia",
        "West Athens",
        "Oakdale",
        "Fillmore",
        "Willowbrook",
        "Oroville",
        "Ridgecrest",
        "South Whittier",
        "Lennox",
        "Livingston",
        "Ceres",
        "Marysville",
        "Bay Point",
        "Red Bluff",
        "Fortuna",
        "West Carson",
        "Los Banos",
        "San Joaquin County",
        "Stevenson Ranch",
        "San Francisco County",
        "Mono County",
        "Del Norte County",
        "Calaveras County",
        "Santa Barbara County",
        "Castaic",
        "Antelope",
        "Stanislaus County",
        "Tulare County",
        "Universal City",
        "Temecula Ranchos",
        "Mariposa County",
        "East Compton",
        "Valley Center",
        "Riverdale",
        "Magalia",
        "Irwindale",
        "Vernon",
        "Woodland Hills",
        "West Hills",
        "Canoga Park",
        "San Jacinto",
        "Susanville",
        "Shasta Lake",
        "Alpine",
        "Quartz Hill",
        "Tehachapi",
        "Norco",
        "San Lorenzo",
        "Chowchilla",
        "Porterville",
        "Lompoc",
        "Delano",
        "Fairview",
        "Spring Valley",
        "American Canyon",
        "Turlock",
        "Greenfield",
        "Gonzales",
        "Desert Hot Springs",
        "Clearlake",
        "King City",
        "Yucca Valley",
        "Hanford",
        "Ripon",
        "Brawley",
        "Banning",
        "Port Hueneme",
        "Dixon",
        "Rosemont",
        "Lemoore",
        "Kingsburg",
        "Arvin",
        "Atwater",
        "Dinuba",
        "Selma",
        "Anderson",
        "Kerman",
        "Exeter",
        "South Yuba City",
        "Grand Terrace",
        "East Whittier",
        "Bonita",
        "Camp Pendleton North",
        "Tuolumne County",
        "Ben Lomond",
        "Amador County",
        "Leona Valley",
        "Yolo County",
        "Live Oak",
        "Boulder Creek",
        "Sierra County",
        "Solano County",
        "Tehama County",
        "Felton",
        "Glenn County",
        "Plumas County",
        "Acton",
        "La Habra Heights",
        "La Crescenta-Montrose",
        "Pearblossom",
        "Lassen County",
        "Pauma Valley",
        "Jamul",
        "Inyo County",
        "Bonsall",
        "Julian",
        "Foothill Farms",
        "Yuba County",
        "Modoc County",
        "Imperial County",
        "Fresno County",
        "Hood",
        "West Menlo Park",
        "Trinity County",
        "Pescadero",
        "Rancho Murieta",
        "El Granada",
        "San Benito County",
        "Dunlap",
        "Moss Beach",
        "Redman",
        "Aptos Hills-Larkin Valley",
        "La Selva Beach",
        "Del Rey",
        "Miramar",
        "Fruitdale",
        "Loma Mar",
        "La Honda",
        "Gold River",
        "Hidden Hills",
        "La Jolla Ranch",
        "Corralitos",
        "Rolling Hills",
        "Redwood Park",
        "Bermuda Dunes",
        "Littlerock",
        "Agua Dulce",
        "Colusa County",
        "Moreno",
        "Caruthers",
        "Lake San Marcos",
        "Dulzura",
        "Camp Pendleton South",
        "Freedom",
        "Mountain Center",
        "Rainbow",
        "San Felipe",
        "McClellan Park",
        "Fowler",
        "Montara",
        "White Rock",
        "Palos Verdes Peninsula",
        "Castaic Junction",
        "Descanso",
        "Valinda",
        "San Joaquin",
        "Cornell",
        "Davenport",
        "La Crescenta",
        "Newhall",
        "Friant",
        "Canyon Country",
        "Amesti",
        "Firebaugh",
        "Arden-Arcade",
        "Madrone",
        "Coyote",
        "North Fair Oaks",
        "Highlands-Baywood Park",
        "Robertsville",
        "Alamitos",
        "Evergreen",
        "Minkler",
        "Valencia",
        "San Pedro",
        "East Foothills",
        "Forest Ranch",
        "Valyermo",
        "Hume",
        "Herald",
        "Bradbury",
        "Oregon City",
        "Isleton",
        "Wildflower",
        "Lilac",
        "Avocado",
        "Auberry",
        "El Camino Village",
        "Alum Rock",
        "Elizabeth Lake",
        "Interlaken",
        "Raisin City",
        "Lompico",
        "Coalinga",
        "Hillsdale",
        "La Presa",
        "Ladera Heights",
        "Laton",
        "Sloughhouse",
        "Val Verde",
        "English Town",
        "Highway City",
        "Florin",
        "Blossom Valley"
    },
    "TX": {
        "Austin",
        "Travis County",
        "Dallas",
        "Harris County",
        "Houston",
        "San Antonio",
        "Fort Worth",
        "Plano",
        "Irving",
        "Texas City",
        "Frisco",
        "Arlington",
        "Odessa",
        "The Woodlands",
        "Richardson",
        "El Paso",
        "College Station",
        "Pasadena",
        "Waco",
        "Southlake",
        "Allen",
        "Addison",
        "Carrollton",
        "Lubbock",
        "San Marcos",
        "Round Rock",
        "Sugar Land",
        "Laredo",
        "Corpus Christi",
        "Conroe",
        "Amarillo",
        "Katy",
        "Tyler",
        "Lewisville",
        "Beaumont",
        "Collin County",
        "Longview",
        "Flower Mound",
        "Midland",
        "Denton",
        "Paris",
        "Cedar Park",
        "Nederland",
        "Hidalgo County",
        "Bryan",
        "Georgetown",
        "Milam County",
        "Mesquite",
        "Coppell",
        "Keller",
        "Killeen",
        "Spring",
        "Grapevine",
        "Temple",
        "Galveston",
        "Brownsville",
        "Mission",
        "Colleyville",
        "Mansfield",
        "Missouri City",
        "Abilene",
        "Humble",
        "South Houston",
        "Wichita Falls",
        "Garland",
        "New Braunfels",
        "San Angelo",
        "League City",
        "Huntsville",
        "Bedford",
        "Pearland",
        "Webster",
        "Stafford",
        "Grand Prairie",
        "Schertz",
        "Weslaco",
        "Burnet County",
        "Kyle",
        "Edinburg",
        "Little Elm",
        "Friendswood",
        "Euless",
        "Kerrville",
        "Richmond",
        "Rockport",
        "Pflugerville",
        "Sherman",
        "Wylie",
        "Rockwall",
        "Rowlett",
        "Leander",
        "Waxahachie",
        "Watauga",
        "Weatherford",
        "Port Arthur",
        "Balch Springs",
        "Burleson",
        "Lancaster",
        "Tomball",
        "The Colony",
        "Hays County",
        "Denton County",
        "Dallas County",
        "Cass County",
        "Farmers Branch",
        "DeSoto",
        "Hewitt",
        "Harlingen",
        "Hurst",
        "Brenham",
        "Victoria",
        "Pharr",
        "Lakeway",
        "Universal City",
        "Cypress",
        "Seagoville",
        "Dickinson",
        "Big Spring",
        "Henderson County",
        "Tarrant County",
        "Ellis County",
        "Montgomery County",
        "Wood County",
        "Hood County",
        "McLennan County",
        "Lamb County",
        "Sulphur Springs",
        "Seabrook",
        "Texarkana",
        "Canyon Lake",
        "Alvin",
        "Highland Park",
        "Portland",
        "Nacogdoches",
        "La Porte",
        "Angleton",
        "Lumberton",
        "Bridge City",
        "Galena Park",
        "Lufkin",
        "Saginaw",
        "Lake Jackson",
        "Deer Park",
        "Sachse",
        "West Odessa",
        "Baytown",
        "Wharton",
        "Mineral Wells",
        "Uvalde",
        "Cleburne",
        "Cedar Hill",
        "Bellaire",
        "Alice",
        "Sweetwater",
        "Crowley",
        "Taylor",
        "Live Oak",
        "Duncanville",
        "Haltom City",
        "Brownfield",
        "Corinth",
        "Mount Pleasant",
        "Lockhart",
        "Plainview",
        "Kaufman County",
        "Wise County",
        "Hunt County",
        "Grayson County",
        "Dickens County",
        "Kendall County",
        "Angelina County",
        "Bastrop County",
        "Comal County",
        "Canton",
        "Johnson County",
        "Bexar County",
        "Caldwell County",
        "Columbus",
        "Red River County",
        "Delta County",
        "Calhoun County",
        "Terrell",
        "Pleasanton",
        "Fredericksburg",
        "University Park",
        "Aransas Pass",
        "Rosenberg",
        "Greenville",
        "Atascocita",
        "Midlothian",
        "Belton",
        "Copperas Cove",
        "Denison",
        "Hereford",
        "Graham",
        "North Richland Hills",
        "Marshall",
        "Kingsville",
        "Eagle Pass",
        "Harker Heights",
        "Converse",
        "Seguin",
        "Dumas",
        "Port Neches",
        "White Settlement",
        "Ingleside",
        "Kilgore",
        "Commerce",
        "Benbrook",
        "Canyon",
        "Bonham",
        "Highland Village",
        "Gainesville",
        "Santa Fe",
        "Alamo",
        "Stephenville",
        "Rio Grande City",
        "Robinson",
        "Bay City",
        "Del Rio",
        "Azle",
        "Ennis",
        "Port Lavaca",
        "Woodway",
        "West University Place",
        "Mercedes",
        "Corsicana",
        "Cloverleaf",
        "Brownwood",
        "Kirby",
        "Bandera County",
        "Brazoria County",
        "Rockwall County",
        "Hansford County",
        "Montague County",
        "Wharton County",
        "Galveston County",
        "Smith County",
        "Young County",
        "Hockley County",
        "Shelby County",
        "Somervell County",
        "Hutchins",
        "Cameron County",
        "Bowie County",
        "Waller County",
        "Orange County",
        "Madison County",
        "Williamson County",
        "Parker County",
        "Reagan County",
        "Terry County",
        "Brown County",
        "Burleson County",
        "Hale County",
        "Fayette County",
        "Wills Point",
        "Llano County",
        "Palo Pinto County",
        "Wilbarger County",
        "Carson County",
        "Brewster County",
        "Liberty County",
        "Scurry County",
        "Franklin County",
        "Polk County",
        "Jones County",
        "Atascosa County",
        "Real County",
        "Kerr County",
        "Sherman County",
        "Comanche County",
        "Hill County",
        "Pecos County",
        "Nueces County",
        "Austin County",
        "Jefferson County",
        "Grimes County",
        "Sabine County",
        "Matagorda County",
        "Ward County",
        "Orange",
        "Anderson County",
        "El Paso County",
        "Bailey County",
        "Panola County",
        "Upshur County",
        "Callahan County",
        "Lubbock County",
        "Andrews",
        "Fort Bliss",
        "Walker County",
        "Los Angeles",
        "Ochiltree County",
        "Cat Spring",
        "Guadalupe County",
        "Cee Vee",
        "Wallis",
        "Cooke County",
        "Jasper",
        "Rusk County",
        "Foard County",
        "Lamar County",
        "Camp County",
        "Normangee",
        "Zavala County",
        "Eastland County",
        "Knox County",
        "Bell County",
        "Kleberg County",
        "Cherokee County",
        "Edwards County",
        "Electra",
        "Baylor County",
        "Morris County",
        "Lytle",
        "Gray County",
        "Webb County",
        "McCulloch County",
        "Limestone County",
        "Robertson County",
        "Hall County",
        "Fannin County",
        "DeWitt County",
        "Perrin",
        "Refugio County",
        "Freestone County",
        "Centerville",
        "Vidor",
        "Yoakum County",
        "Wilson County",
        "Grand Saline",
        "Cochran County",
        "Eagle Lake",
        "Stephens County",
        "Chambers County",
        "Harrison County",
        "Castroville",
        "Glenn Heights",
        "Garrison",
        "Wolfforth",
        "Upton County",
        "Kimble County",
        "Jim Wells County",
        "Nolan County",
        "Ladonia",
        "Savoy",
        "Friona",
        "Martin County",
        "Waelder",
        "Washington County",
        "Blanco County",
        "Van",
        "San Augustine County",
        "Lovelady",
        "Goliad County",
        "Posey",
        "Jeff Davis County",
        "Glasscock County",
        "Presidio County",
        "Kenedy County",
        "Briarcliff",
        "Devine",
        "Sterling County",
        "Byers",
        "Iowa Park",
        "Castro County",
        "Winkler County",
        "Shallowater",
        "Hico",
        "Douglass",
        "Aransas County",
        "Zapata County",
        "Inez",
        "Jim Hogg County",
        "Haskell County",
        "Hamilton",
        "Nixon",
        "Duval County",
        "Starr County",
        "Clint",
        "Titus County",
        "Jonestown",
        "Honey Grove",
        "Mills County",
        "Culberson County",
        "Groveton",
        "Crosby County",
        "Socorro",
        "New Sweden",
        "Godley",
        "Jackson County",
        "Flo",
        "Dubina",
        "Gaines County",
        "Newton County",
        "Van Zandt County",
        "Donley County",
        "Roberts County",
        "Claude",
        "Lipscomb County",
        "Potter County",
        "Oldham County",
        "Swisher County",
        "Nursery",
        "Ivanhoe",
        "Fayetteville",
        "King County",
        "Wheeler County",
        "Fabens",
        "Henrietta",
        "Artesia Wells",
        "Mason",
        "China",
        "Hamshire",
        "Carmine",
        "Borden County",
        "Cut",
        "Telephone",
        "Garwood"
    }
}
