"""Module BAD SITES."""


BAD_DOMAINS = [
    ".af", ".ax", ".al", ".as", ".ad", ".ao", ".ai", ".ag", ".ar", ".am", ".ac", ".au", ".at",
    ".az", ".bs", ".bh", ".bd", ".bb", ".be", ".bz", ".bj", ".bm", ".bt", ".bo", ".ba", ".bw",
    ".bv", ".br", ".io", ".vg", ".bn", ".bg", ".bf", ".mm", ".bi", ".cm", ".ca", ".cv", ".cat",
    ".ky", ".cf", ".cl", ".cn", ".cx", ".cc", ".co", ".cd", ".cg", ".ck", ".cr", ".ci", ".cu",
    ".cw", ".cy", ".cz", ".dk", ".dj", ".dm", ".do", ".ec", ".eg", ".sv", ".et", ".eu", ".fk",
    ".fm", ".fj", ".fi", ".fr", ".ga", ".gal", ".gm", ".ge", ".gh", ".gi", ".gr", ".gl", ".gd",
    ".gp", ".gu", ".gt", ".gg", ".gn", ".gw", ".gy", ".ht", ".hm", ".hn", ".hk", ".hu", ".in",
    ".id", ".ir", ".iq", ".ie", ".im", ".il", ".it", ".jm", ".jp", ".je", ".jo", ".kz", ".ke",
    ".ki", ".kw", ".kg", ".la", ".lv", ".lb", ".ls", ".lr", ".ly", ".li", ".lt", ".lu", ".mg",
    ".mw", ".my", ".mv", ".ml", ".mt", ".mh", ".mq", ".mr", ".mu", ".yt", ".mx", ".md", ".mc",
    ".mn", ".me", ".ms", ".mz", ".mm", ".na", ".nr", ".np", ".nl", ".nc", ".nz", ".ni", ".ne",
    ".ng", ".nu", ".nf", ".mp", ".no", ".om", ".pk", ".ps", ".pa", ".pg", ".py", ".pe", ".ph",
    ".pn", ".pl", ".pt", ".pr", ".qa", ".ro", ".ru", ".rw", ".re", ".sh", ".kn", ".lc", ".pm",
    ".vc", ".sm", ".st", ".sa", ".sn", ".sc", ".sl", ".sg", ".sk", ".si", ".so", ".so", ".gs",
    ".kr", ".ss", ".lk", ".sd", ".sr", ".sj", ".sz", ".se", ".ch", ".sy", ".tw", ".tj", ".tz",
    ".th", ".tg", ".tk", ".to", ".tt", ".tn", ".tr", ".tm", ".tc", ".tv", ".ug", ".ae", ".uk",
    ".us", ".vi", ".uy", ".uz", ".vu", ".va", ".ve", ".vn", ".wf", ".ye", ".zm", ".zw", ".ace",
    ".ani", ".arc", ".arj", ".avi", ".bh", ".bmp", ".cab", ".cla", ".class", ".css", ".exe",
    ".gif", ".gz", ".ico", ".jar", ".jpeg", ".jpg", ".lha", ".mid", ".mov", ".mp2", ".mp3",
    ".mpeg", ".mpg", ".pdf", ".png", ".rar", ".riff", ".rmi", ".tar", ".tif", ".tiff", ".wav",
    ".xbm", ".z", ".zip", "altavista.com", "answers.com", "dictionary.reference.com",
    ".google.com", ".googleadservices.com", ".msn.com", ".w3.org", ".yahoo.com"
]

BAD_EMAILS = [
    ".gif",
    ".htm",
    ".html",
    ".jpeg",
    ".jpg",
    ".php",
    ".png",
    ".@.apps.messenger.live.com",
    ".@.google.com",
    ".@.googlegroups.com",
    ".@company.com",
    ".@example.com",
    ".@fraudtest.com",
    ".@youremail.com",
    "@anydomain",
    "@yourdomain",
    "yourname",
    "@yourname.com",
    "abuse",
    "antispam",
    "anyone@.",
    "bbb@cc.com",
    "bugtraq",
    "daemon",
    "ezine",
    "fidonet",
    "fraud",
    "illegel.com",
    "junk",
    "listserv",
    "mailer-daemon",
    "majordomo",
    "nospam",
    "postmaster",
    "privacy",
    "remove",
    "removeme",
    "renigade@mediaone.net",
    "ripoff",
    "scam",
    "spam",
    "spamcop",
    "spamcop.net",
    "subscribe",
    "support@ours.com",
    "unsubscribe",
    "username@.",
    "your@email.com",
    "yourdomain"
]
